create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists rooms (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists assets (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references rooms(id) on delete cascade,
  title text not null,
  current_version text not null,
  image_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  edited_by text not null
);

create table if not exists asset_tags (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid not null references assets(id) on delete cascade,
  tag text not null
);

create table if not exists asset_versions (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid not null references assets(id) on delete cascade,
  version text not null,
  prompt text not null,
  size text not null,
  style text not null,
  notes text,
  editor text not null,
  created_at timestamptz not null default now()
);

create table if not exists annotations (
  id bigint generated by default as identity primary key,
  asset_id uuid not null references assets(id) on delete cascade,
  number integer not null,
  x_position numeric not null,
  y_position numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists comments (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid not null references assets(id) on delete cascade,
  author text not null,
  avatar_url text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists assets_room_id_idx on assets(room_id);
create index if not exists asset_tags_asset_id_idx on asset_tags(asset_id);
create index if not exists asset_versions_asset_id_idx on asset_versions(asset_id);
create index if not exists annotations_asset_id_idx on annotations(asset_id);
create index if not exists comments_asset_id_idx on comments(asset_id);

create unique index if not exists asset_versions_unique_version_idx on asset_versions(asset_id, version);
create unique index if not exists annotations_asset_number_idx on annotations(asset_id, number);

alter table rooms enable row level security;
alter table assets enable row level security;
alter table asset_tags enable row level security;
alter table asset_versions enable row level security;
alter table annotations enable row level security;
alter table comments enable row level security;

drop policy if exists "rooms_public_read" on rooms;
create policy "rooms_public_read" on rooms
for select to public
using (true);

drop policy if exists "rooms_authenticated_write" on rooms;
create policy "rooms_authenticated_write" on rooms
for all to authenticated
using (true)
with check (true);

drop policy if exists "assets_public_read" on assets;
create policy "assets_public_read" on assets
for select to public
using (true);

drop policy if exists "assets_authenticated_write" on assets;
create policy "assets_authenticated_write" on assets
for all to authenticated
using (true)
with check (true);

drop policy if exists "asset_tags_public_read" on asset_tags;
create policy "asset_tags_public_read" on asset_tags
for select to public
using (true);

drop policy if exists "asset_tags_authenticated_write" on asset_tags;
create policy "asset_tags_authenticated_write" on asset_tags
for all to authenticated
using (true)
with check (true);

drop policy if exists "asset_versions_public_read" on asset_versions;
create policy "asset_versions_public_read" on asset_versions
for select to public
using (true);

drop policy if exists "asset_versions_authenticated_write" on asset_versions;
create policy "asset_versions_authenticated_write" on asset_versions
for all to authenticated
using (true)
with check (true);

drop policy if exists "annotations_public_read" on annotations;
create policy "annotations_public_read" on annotations
for select to public
using (true);

drop policy if exists "annotations_authenticated_write" on annotations;
create policy "annotations_authenticated_write" on annotations
for all to authenticated
using (true)
with check (true);

drop policy if exists "comments_public_read" on comments;
create policy "comments_public_read" on comments
for select to public
using (true);

drop policy if exists "comments_authenticated_write" on comments;
create policy "comments_authenticated_write" on comments
for all to authenticated
using (true)
with check (true);

drop trigger if exists rooms_set_updated_at on rooms;
create trigger rooms_set_updated_at
before update on rooms
for each row
execute function public.set_updated_at();

drop trigger if exists assets_set_updated_at on assets;
create trigger assets_set_updated_at
before update on assets
for each row
execute function public.set_updated_at();

insert into storage.buckets (id, name, public)
values ('asset-images', 'asset-images', true)
on conflict (id) do nothing;

drop policy if exists "asset_images_public_read" on storage.objects;
create policy "asset_images_public_read"
on storage.objects
for select to public
using (bucket_id = 'asset-images');

drop policy if exists "asset_images_authenticated_write" on storage.objects;
create policy "asset_images_authenticated_write"
on storage.objects
for all to authenticated
using (bucket_id = 'asset-images')
with check (bucket_id = 'asset-images');

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'rooms'
  ) then
    execute 'alter publication supabase_realtime add table public.rooms';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'assets'
  ) then
    execute 'alter publication supabase_realtime add table public.assets';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'asset_tags'
  ) then
    execute 'alter publication supabase_realtime add table public.asset_tags';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'asset_versions'
  ) then
    execute 'alter publication supabase_realtime add table public.asset_versions';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'annotations'
  ) then
    execute 'alter publication supabase_realtime add table public.annotations';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'comments'
  ) then
    execute 'alter publication supabase_realtime add table public.comments';
  end if;
end $$;
